"""Load whale-tutor.config.yaml and convert to env vars for the Node server.

Config schema (see template generated by `whale-tutor init`):

    courses_dir: ./courses
    database:
      host: localhost
      port: 13306
      user: tutor
      password: tutor
      database: whale_tutor
    ai:
      deepseek_api_key: sk-xxxxx
      deepseek_api_base_url: https://api.deepseek.com
    server:
      port: 3000
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import yaml

CONFIG_FILENAME = "whale-tutor.config.yaml"


@dataclass
class DatabaseConfig:
    host: str = "localhost"
    port: int = 13306
    user: str = "tutor"
    password: str = "tutor"
    database: str = "whale_tutor"


@dataclass
class AiConfig:
    deepseek_api_key: str = ""
    deepseek_api_base_url: str = "https://api.deepseek.com"


@dataclass
class ServerConfig:
    port: int = 3000


@dataclass
class WhaleTutorConfig:
    courses_dir: Path
    database: DatabaseConfig = field(default_factory=DatabaseConfig)
    ai: AiConfig = field(default_factory=AiConfig)
    server: ServerConfig = field(default_factory=ServerConfig)
    # 配置文件本身的路径,用于把 courses_dir 等相对路径解析为绝对
    config_path: Path = field(default_factory=Path)


def find_config(start: Optional[Path] = None) -> Path:
    """从 start (默认 cwd) 向上找 whale-tutor.config.yaml。找不到抛 FileNotFoundError。"""
    cur = (start or Path.cwd()).resolve()
    while True:
        candidate = cur / CONFIG_FILENAME
        if candidate.exists():
            return candidate
        if cur.parent == cur:  # 根目录
            raise FileNotFoundError(
                f"找不到 {CONFIG_FILENAME}。请在课程根目录运行,或先跑 `whale-tutor init`。"
            )
        cur = cur.parent


def load_config(config_path: Path) -> WhaleTutorConfig:
    """读 yaml + 解析路径 + 应用环境变量 override。返回完整配置。"""
    with open(config_path, "r", encoding="utf-8") as f:
        raw = yaml.safe_load(f) or {}

    config_dir = config_path.parent

    # courses_dir 相对 config 文件所在位置
    courses_dir_raw = raw.get("courses_dir", "./courses")
    courses_dir = (config_dir / courses_dir_raw).resolve()

    db_raw = raw.get("database", {}) or {}
    database = DatabaseConfig(
        host=os.environ.get("DATABASE_HOST", db_raw.get("host", "localhost")),
        port=int(os.environ.get("DATABASE_PORT", db_raw.get("port", 13306))),
        user=os.environ.get("DATABASE_USER", db_raw.get("user", "tutor")),
        password=os.environ.get("DATABASE_PASSWORD", db_raw.get("password", "tutor")),
        database=os.environ.get(
            "DATABASE_NAME", db_raw.get("database", "whale_tutor")
        ),
    )

    ai_raw = raw.get("ai", {}) or {}
    ai = AiConfig(
        deepseek_api_key=os.environ.get(
            "DEEPSEEK_API_KEY", ai_raw.get("deepseek_api_key", "")
        ),
        deepseek_api_base_url=os.environ.get(
            "DEEPSEEK_API_BASE_URL",
            ai_raw.get("deepseek_api_base_url", "https://api.deepseek.com"),
        ),
    )

    server_raw = raw.get("server", {}) or {}
    server = ServerConfig(
        port=int(os.environ.get("SERVER_PORT", server_raw.get("port", 3000))),
    )

    return WhaleTutorConfig(
        courses_dir=courses_dir,
        database=database,
        ai=ai,
        server=server,
        config_path=config_path.resolve(),
    )


def to_env(cfg: WhaleTutorConfig, *, web_dir: Path, schema_file: Path) -> dict:
    """把配置转成给 node 子进程的环境变量字典。"""
    return {
        "DATABASE_HOST": cfg.database.host,
        "DATABASE_PORT": str(cfg.database.port),
        "DATABASE_USER": cfg.database.user,
        "DATABASE_PASSWORD": cfg.database.password,
        "DATABASE_NAME": cfg.database.database,
        "DEEPSEEK_API_KEY": cfg.ai.deepseek_api_key,
        "DEEPSEEK_API_BASE_URL": cfg.ai.deepseek_api_base_url,
        "SERVER_PORT": str(cfg.server.port),
        # server 端 KnowledgeService / ServeStaticModule / schema bootstrap 都靠这三个 env
        "WHALE_TUTOR_COURSES_DIR": str(cfg.courses_dir),
        "WHALE_TUTOR_WEB_DIR": str(web_dir),
        "WHALE_TUTOR_SCHEMA_FILE": str(schema_file),
        # bootstrap schema 由 CLI 在 db.py 里跑过了,server 端不需要再做(也支持环境变量打开二次保险)
        "WHALE_TUTOR_BOOTSTRAP_SCHEMA": "0",
    }
