/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveViewer: typeof import('./src/components/ArchiveViewer.vue')['default']
    CodeSandboxCard: typeof import('./src/components/patterns/CodeSandboxCard.vue')['default']
    ConceptCheckCard: typeof import('./src/components/patterns/ConceptCheckCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FeedbackArea: typeof import('./src/components/FeedbackArea.vue')['default']
    FreeRecallCard: typeof import('./src/components/patterns/FreeRecallCard.vue')['default']
    HintBar: typeof import('./src/components/HintBar.vue')['default']
    InteractionStage: typeof import('./src/components/InteractionStage.vue')['default']
    LoIntroCard: typeof import('./src/components/LoIntroCard.vue')['default']
    ProgressSidebar: typeof import('./src/components/ProgressSidebar.vue')['default']
    QaMessage: typeof import('./src/components/qa/QaMessage.vue')['default']
    QaPanel: typeof import('./src/components/qa/QaPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpotTheBugCard: typeof import('./src/components/patterns/SpotTheBugCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
